# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebde504413f0fd74ead7849da5d7b74ab1317acba3808a6bbeedeb0addaae87f3f8c9f7ed5e28695d85d00904c7702c95c9e716c23d097dbde7302804d4a315e

test:
  secret_key_base: 9ada7cfdd06f23b0d6eeb8dfd5a77c370ff9e3ea12c5949f064ee012d3b851af0cc519dd9b3a4d2c34df7570a8b4761055c1e3bb2087eacfcc1a57a430dc27b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
